import React, { useState } from 'react';
import axios from 'axios';

function StudentForm() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [grades, setGrades] = useState([]);

  const handleSubmit = async (event) => {
    event.preventDefault();
    const gradesArray = grades.split(/[ ,]+/).map(Number); // split grades string into array of numbers
    const res = await axios.post('/api/user/add', { name, email, grades: gradesArray });
    console.log(res.data); // the created document with autogenerated student ID
    // reset form fields
    setName('');
    setEmail('');
    setGrades('');
  };

  return (
    <form onSubmit={handleSubmit} className="w-full max-w-sm mx-auto">
      <div className="mb-4">
        <label className="block text-gray-700 font-bold mb-2" htmlFor="name">
          Name:
        </label>
        <input
          id="name"
          type="text"
          value={name}
          onChange={(event) => setName(event.target.value)}
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          required
        />
      </div>
      <div className="mb-4">
        <label className="block text-gray-700 font-bold mb-2" htmlFor="email">
          Email:
        </label>
        <input
          id="email"
          type="email"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          required
        />
      </div>
      <div className="mb-4">
        <label className="block text-gray-700 font-bold mb-2" htmlFor="grades">
          Grades:
        </label>
        <input
          id="grades"
          type="text"
          value={grades}
          onChange={(event) => setGrades(event.target.value)}
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          required
        />
      </div>
      <div className="flex items-center justify-center">
        <button
          type="submit"
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
        >
          Submit
        </button>
      </div>
    </form>
  );
}

export default StudentForm;
